### ISSUE TITLE
Issue with UPS tracking numbers that start with "105..."

### ISSUE THREAD

**Issue by jap88** [EasyPost/easypost-python#110]
to preface the tracking numbers. Any UPS tracking number that starts with 105... is typically a tracking number for a pallet of things rather than a box. Below is the error i receive along with the code i used to create it.

```
tracker = easypost.Tracker.create(
	tracking_code="1058233044",
	carrier="UPS"
	
)
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    tracker = easypost.Tracker.create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/easypost-4.1.0-py3.8.egg/easypost/__init__.py", line 599, in create
    response, api_key = requestor.request('post', url, wrapped_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/easypost-4.1.0-py3.8.egg/easypost/__init__.py", line 267, in request
    response = self.interpret_response(http_body, http_status)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/easypost-4.1.0-py3.8.egg/easypost/__init__.py", line 328, in interpret_response
    self.handle_api_error(http_status, http_body, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/easypost-4.1.0-py3.8.egg/easypost/__init__.py", line 392, in handle_api_error
    raise Error(error.get('message', ''), http_status, http_body)
easypost.Error: The tracking number does not belong to the carrier you specified. Please confirm that both the carrier and tracking number are correct.
```

i can confirm that the tracking number does belong to UPS. Please let me know if there is any way that we are able to force check the API to use a particular shipping carrier.

**Comment by Roguelazer** [comment]
I have filed this as a task in our internal bug tracker for further investigation.

**Comment by jap88** [comment]
Thank you!

**Comment by Roguelazer** [comment]
Just to circle back: we did some research and it turns out that these tracking codes are for UPS's Freight services, which we currently don't support tracking. We've ticketed building out that integration, but it's non-trivial so it may be a while. Thanks for reporting, though!
