### ISSUE TITLE
'Tracker' object has no attribute 'id'

### ISSUE THREAD

**Issue by mnahta** [EasyPost/easypost-python#111]
The example in your [docs](https://pypi.org/project/easypost/) doesn't work and without any change, our production systems started failing. .

The error is specifically happening in this call somewhere upstream easypost.Shipment.create()

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 600, in create
    return convert_to_easypost_object(response, api_key)
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 150, in convert_to_easypost_object
    return cls.construct_from(response, api_key, parent, name)
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 464, in construct_from
    instance.refresh_from(values, api_key)
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 476, in refresh_from
    self.__dict__[k] = convert_to_easypost_object(v, api_key, self, k)
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 150, in convert_to_easypost_object
    return cls.construct_from(response, api_key, parent, name)
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 464, in construct_from
    instance.refresh_from(values, api_key)
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 471, in refresh_from
    if k == 'id' and self.id != v:
  File "/usr/local/lib/python3.7/site-packages/easypost/__init__.py", line 434, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (type(self).__name__, k))
AttributeError: 'Tracker' object has no attribute 'id'

```

This is the python call

```>>> to_address = easypost.Address.create(
...     verify=["delivery"],
...     name = "Dr. Steve Brule",
...     street1 = "179 N Harbor Dr",
...     street2 = "",
...     city = "Redondo Beach",
...     state = "CA",
...     zip = "90277",
...     country = "US",
...     phone = "310-808-5243"
... )
>>> from_address = easypost.Address.create(
...     verify=["delivery"],
...     name = "EasyPost",
...     street1 = "118 2nd Street",
...     street2 = "4th Floor",
...     city = "San Francisco",
...     state = "CA",
...     zip = "94105",
...     country = "US",
...     phone = "415-456-7890"
... )
>>> parcel = easypost.Parcel.create(
...         predefined_package = "Parcel",
...         weight = 21.2
...     )
>>> shipment = easypost.Shipment.create(
...     to_address = to_address,
...     from_address = from_address,
...     parcel = parcel,)```

**Comment by Roguelazer** [comment]
This is actually a backend issue which we are in the process of remedying. Details can be found at https://www.easypoststatus.com/incidents/mkxmgch2pnd8.

Thanks for reporting!
