### ISSUE TITLE
Adding Insurance Throwing A Circular Import Error

### ISSUE THREAD

**Issue by eliezerp3** [EasyPost/easypost-python#168]
Hi. I am using the following code from the easypost docs:

```python
               import easypost
               easypost.api_key = settings.EASYPOST_KEY
               easypost_from_address = easypost.Address.create(
                    company='My Company',
                    street1=seller_address.address1,
                    street2=seller_address.address2,
                    city=seller_address.city,
                    state=seller_address.state,
                    zip=seller_address.zip_code,
                    # phone='415-528-7555',
                    country='USA', #seller_address.country,
                )

                easypost_to_address = easypost.Address.create(
                    name=to_address['name'],
                    # company='Vandelay Industries',
                    street1=to_address['address1'],
                    street2=to_address['address2'],
                    city=to_address['city'],
                    state=to_address['state'],
                    zip=to_address['zip_code'],
                    country='USA', #to_address['country'],
                )

                easypost_parcel = easypost.Parcel.create(
                    length=length,
                    width=width,
                    height=height,
                    weight=weight,
                )

                shipment = easypost.Shipment.create(
                    to_address=easypost_to_address,
                    from_address=easypost_from_address,
                    parcel=easypost_parcel
                )

                shipment.buy(
                    rate=shipment.lowest_rate(carriers=['USPS'], services=['First']),
                    insurance=price,
                )
```

When i comment out the insurance then it runs fine. But as soon as I add in the insurance I am getting a circular import error. I am using django with the easypost testing key. Here is the console error message:

```
 Internal Server Error: /api/orders/seller/1/create_shipping_label/
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
server_1  |     response = get_response(request)
server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
server_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server_1  |   File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server_1  |     return view_func(*args, **kwargs)
server_1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
server_1  |     return self.dispatch(request, *args, **kwargs)
server_1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
server_1  |     response = self.handle_exception(exc)
server_1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
server_1  |     self.raise_uncaught_exception(exc)
server_1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
server_1  |     raise exc
server_1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
server_1  |     response = handler(request, *args, **kwargs)
server_1  |   File "/app/order/views.py", line 113, in create_shipping_label
server_1  |     shipment.buy(
server_1  |   File "/usr/local/lib/python3.10/site-packages/easypost/__init__.py", line 676, in buy
server_1  |     response, api_key = requestor.request("post", url, params)
server_1  |   File "/usr/local/lib/python3.10/site-packages/easypost/__init__.py", line 207, in request
server_1  |     http_body, http_status, my_api_key = self.request_raw(method, url, params, apiKeyRequired)
server_1  |   File "/usr/local/lib/python3.10/site-packages/easypost/__init__.py", line 259, in request_raw
server_1  |     http_body, http_status = self.requests_request(method, abs_url, headers, params)
server_1  |   File "/usr/local/lib/python3.10/site-packages/easypost/__init__.py", line 282, in requests_request
server_1  |     data = json.dumps(params, default=_utf8)
server_1  |   File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
server_1  |     **kw).encode(obj)
server_1  |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
server_1  |     chunks = self.iterencode(o, _one_shot=True)
server_1  |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
server_1  |     return _iterencode(o, 0)
server_1  | ValueError: Circular reference detected
```

Thank You

**Comment by Justintime50** [comment]
I'm unable to reproduce this error myself. Can you provide me the exact values you are using for the addresses and other variables such as `price` and the parcel dimensions/weight? What does the rest of your logic look like? Having as much information will help us debug this.

I'd also recommend passing in all the data directly to the shipment create call. This will save you an API call for each address creation and the parcel creation greatly speeding up your code.

**Comment by eliezerp3** [comment]
@Justintime50 Quick question tho. Does the from or to address require a phone number to ship?

**Comment by Justintime50** [comment]
That depends on the carrier and/or destination. For those kinds of questions, the best resource will be our support team which can be reached at support@easypost.com. Best of luck!
